version: '3.8'

services:
  web:
    build:
      context: .
    env_file:
      - src/env/dev/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=banking_api
      - POSTGRES_PASSWORD=banking_api
      - POSTGRES_DB=banking_api
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgressql/data
      
volumes:
  postgres-db:
